import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { ESLint } from "eslint";

const root = fileURLToPath(new URL("../../", import.meta.url));
const biome = join(root, "node_modules/.bin/biome");

async function fixture(directory: string, path: string, contents: string): Promise<void> {
  await mkdir(dirname(join(directory, path)), { recursive: true });
  await writeFile(join(directory, path), contents);
}

async function formatFixture(
  directory: string,
  included: readonly string[],
  excluded: readonly string[],
  invalid: string,
) {
  const run = () => spawnSync(biome, ["format", "--write", "."], { cwd: directory });
  assert.equal(run().status, 0);
  const formatted = await Promise.all(included.map((path) => readFile(join(directory, path), "utf8")));
  for (const value of formatted) assert.notEqual(value, invalid);
  for (const path of excluded) assert.equal(await readFile(join(directory, path), "utf8"), invalid);
  assert.equal(run().status, 0);
  assert.deepEqual(await Promise.all(included.map((path) => readFile(join(directory, path), "utf8"))), formatted);
}

const included = [
  "packages/core/src/probe.ts",
  "packages/geometry/src/probe.ts",
  "packages/svg/src/probe.ts",
  "packages/fontkit/src/probe.ts",
  "apps/node/probe.ts",
  "apps/showcase/src/probe.ts",
  "scripts/probe.ts",
  "tests/probe.test.ts",
  "apps/browser-fonts/probe.d.ts",
  "eslint.config.ts",
];
const excluded = [
  "packages/legacy/probe.ts",
  "docs/evidence/probe.ts",
  "docs/roadmap/probe.ts",
  "archive/probe.ts",
  "packages/core/dist/probe.ts",
  "apps/node/dist-proof/probe.ts",
  "apps/node/build/probe.ts",
  "apps/node/out/probe.ts",
  "scripts/artifacts/probe.ts",
  "tests/node_modules/probe.ts",
  "tests/ignored/probe.ts",
  "packages/core/package-lock.json",
  "tests/fixtures/fonts/liberation-sans.json",
  "scripts/archive/probe.ts",
  "apps/node/snapshots/probe.ts",
  "packages/core/__snapshots__/probe.ts",
  "scripts/generated-reports/probe.ts",
];
test("Biome includes native code, tests, declarations and configs but excludes preserved/generated bytes", async () => {
  const directory = await mkdtemp("/tmp/opencode/updf-biome-");
  const invalid = "export const probe:any=1;\n";
  try {
    await mkdir(join(directory, ".git"));
    await fixture(directory, "biome.json", await readFile(join(root, "biome.json"), "utf8"));
    await fixture(directory, ".gitignore", "tests/ignored/\n");
    for (const path of [...included, ...excluded]) await fixture(directory, path, invalid);
    const result = spawnSync(biome, ["check", "--diagnostic-level=error", "--max-diagnostics=200", "."], {
      cwd: directory,
      encoding: "utf8",
    });
    assert.equal(result.status, 1);
    const diagnostics = result.stdout + result.stderr;
    for (const path of included) assert.ok(diagnostics.includes(`${path}:1:`), `Not checked: ${path}`);
    for (const path of excluded) assert.ok(!diagnostics.includes(`${path}:1:`), `Unexpected scope: ${path}`);
    assert.ok(diagnostics.includes("noExplicitAny"));
    await formatFixture(directory, included, excluded, invalid);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test("ESLint rejects 401-line files, 50-line functions and fourth-level nesting without blanket exemptions", async () => {
  const eslint = new ESLint({ cwd: root });
  const cases = [
    { rule: "max-lines", code: Array.from({ length: 401 }, (_, i) => `export const value${i} = ${i};`).join("\n") },
    { rule: "max-lines-per-function", code: `export function probe() {\n${"  void 0;\n".repeat(48)}}` },
    {
      rule: "max-depth",
      code: "export function probe(x: boolean) { if(x) { if(x) { if(x) { if(x) { void 0; } } } } }",
    },
  ];
  for (const filePath of [
    "packages/core/src/probe.ts",
    "apps/node/probe.ts",
    "apps/showcase/src/probe.ts",
    "scripts/probe.ts",
    "tests/probe.test.ts",
  ]) {
    for (const item of cases) {
      const results = await eslint.lintText(item.code, { filePath });
      assert.ok(
        results[0]?.messages.some((message) => message.ruleId === item.rule),
        `${filePath}: ${item.rule}`,
      );
    }
  }
});
