import { render } from "@updf/core";
import { createUnicodeCmrDocument } from "@updf/example-cmr/cmr-unicode";
import { prepareFont } from "@updf/fontkit";
import fontUrl from "../../tests/fixtures/fonts/LiberationSans-Regular.ttf?url";
import { mountBlockProof } from "./block-proof.js";
import { mountDeferredTableProof } from "./deferred-table-proof.js";
import { numericalFlowProof } from "./flow-numerical-proof.js";
import { flowProof } from "./flow-proof.js";
import { mountInlineProof } from "./inline-proof.js";
import { mountMixedProof } from "./mixed-proof.js";
import { richProof } from "./rich-proof.js";
import { tableProof } from "./table-proof.js";

const fontBytes = new Uint8Array(await (await fetch(fontUrl)).arrayBuffer());
const font = prepareFont(fontBytes);
const bytes = render(createUnicodeCmrDocument(font), { resources: { CmrFont: font } });
const url = URL.createObjectURL(new Blob([bytes], { type: "application/pdf" }));
const status = document.getElementById("status");
if (!status) throw new Error("Missing proof status");
status.textContent = "Browser parsed the TTF and generated the Unicode PDF.";
const link = document.createElement("a");
link.href = url;
link.download = "cmr-unicode.pdf";
link.textContent = "Download Unicode CMR PDF";
link.style.display = "block";
link.style.margin = "1rem 0";
document.body.append(link);
const viewer = document.createElement("object");
viewer.type = "application/pdf";
viewer.data = url;
viewer.width = "750";
viewer.height = "1000";
viewer.style.display = "block";
document.body.append(viewer);
window.addEventListener("pagehide", () => URL.revokeObjectURL(url), { once: true });
const rich = richProof(font);
const richUrl = URL.createObjectURL(new Blob([rich.bytes], { type: "application/pdf" }));
const richLink = document.createElement("a");
richLink.href = richUrl;
richLink.textContent = "Download rich font proof";
richLink.download = "rich-font-browser.pdf";
document.body.append(richLink);
const measured = document.createElement("pre");
measured.id = "rich-measurement";
measured.textContent = JSON.stringify(rich.measurement);
document.body.append(measured);
window.addEventListener("pagehide", () => URL.revokeObjectURL(richUrl), { once: true });
const flow = flowProof(font);
const flowUrl = URL.createObjectURL(new Blob([flow.bytes], { type: "application/pdf" }));
const flowLink = document.createElement("a");
flowLink.href = flowUrl;
flowLink.textContent = "Download flow font proof";
flowLink.download = "flow-font-browser.pdf";
document.body.append(flowLink);
const flowed = document.createElement("pre");
flowed.id = "flow-result";
flowed.textContent = JSON.stringify(flow.result);
document.body.append(flowed);
window.addEventListener("pagehide", () => URL.revokeObjectURL(flowUrl), { once: true });
const numerical = document.createElement("pre");
numerical.id = "flow-numerical-proof";
// Full byte-parity evidence is test data, not an unbounded-width visual preview.
numerical.hidden = true;
numerical.textContent = JSON.stringify(numericalFlowProof(font));
document.body.append(numerical);
const table = tableProof(font);
const tableUrl = URL.createObjectURL(new Blob([table.bytes], { type: "application/pdf" }));
const tableLink = document.createElement("a");
tableLink.href = tableUrl;
tableLink.textContent = "Download table font proof";
tableLink.download = "table-font-browser.pdf";
document.body.append(tableLink);
const tableResult = document.createElement("pre");
tableResult.id = "table-result";
tableResult.textContent = JSON.stringify(table.result);
document.body.append(tableResult);
window.addEventListener("pagehide", () => URL.revokeObjectURL(tableUrl), { once: true });
mountBlockProof();
mountInlineProof(font);
mountMixedProof(font);
mountDeferredTableProof(font);
